name: karCI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
    - pipeline
    paths:
    - test/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: test_env_1
    defaults:
      run:
        shell: bash
        working-directory: test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    #  - name: Dump GitHub context
    #    env:
    #      GITHUB_CONTEXT: ${{ toJSON(github) }}
    #    run: echo "$GITHUB_CONTEXT"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.ref }}

      # Runs a single command using the runners shell
      - name: ls cwd
        run: pwd; ls -l ./
      
      #- uses: actions/download-artifact@v2
      #  id: download
      #  continue-on-error: true
      #  with:
      #    name: test-private-key
          #path: test/artifacts
      #- name: check ssh key existance
      #  id: check-key-existance
      #  run: |
      #    OUTPUT=0; if [[ -f "./testkey" ]]; then OUTPUT=1; fi &&
      #    echo "::set-output name=OUTPUT::$OUTPUT"
      - name: dump secrets
        env:
          SECRETS: ${{ toJSON(secrets) }}
        run: | 
          echo $SECRETS
      - name: dump actors secret
        env:
          SECRET: ${{ toJSON(secrets)['SERIMIKAYELYAN_SECRET'] }}
        run: | 
          echo $SECRET
      - name: create public key
        #if: steps.check-key-existance.outputs.OUTPUT == 0
        run: |
          cat << EOF > sshkey
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          chmod 400 ./sshkey
          ssh-keygen -y -f ./sshkey -N "" > sshkey.pub
      - name: Archive ssh public key
        uses: actions/upload-artifact@v2
        #if: steps.check-key-existance.outputs.OUTPUT == 0
        with:
          name: test-private-key
          path: test/sshkey
      - name: ls cwd
        run: pwd; ls -l ./
     # - name: Dump GitHub context
     #   env:
     #     GITHUB_CONTEXT: ${{ toJSON(github) }}
     #   run: echo "$GITHUB_CONTEXT"
     # - name: dump secrets
     #   env:
     #     SECRETS_CONTEXT: ${{ toJSON(secrets) }}
     #   run: echo "$SECRETS_CONTEXT"
      - name: run test.py
        run: python ./test.py
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
